{
    "name": "CDU eLMIS Integration",
    "summary": "OpenLMIS stock management foundation for the CDU workflow",
    "version": "16.0.1.0.0",
    "category": "Healthcare",
    "author": "Ministry of Health",
    "license": "LGPL-3",
    "depends": [
        "cdu_prescription",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/cdu_elmis_defaults.xml",
        "data/cdu_dispense_sequence.xml",
        "data/cdu_bagging_qa_sequence.xml",
        "data/cdu_box_sequence.xml",
        "wizards/cdu_elmis_auth_wizard_views.xml",
        "views/cdu_dispense_views.xml",
        "views/cdu_bagging_qa_views.xml",
        "views/cdu_box_views.xml",
        "views/cdu_elmis_settings_views.xml",
        "views/cdu_elmis_api_log_views.xml",
        "views/cdu_elmis_stock_cache_views.xml",
        "views/cdu_elmis_user_views.xml",
        "reports/cdu_picking_list_report.xml",
        "reports/cdu_dispense_label_report.xml",
        "views/cdu_elmis_batch_views.xml",
        "views/cdu_elmis_menus.xml",
    ],
    "installable": True,
    "application": False,
}
