{
    "name": "CDU Prescription",
    "summary": "Central Dispensing Unit prescription capture and workflow foundation",
    "version": "16.0.1.0.0",
    "category": "Healthcare",
    "author": "Ministry of Health",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "product",
        "stock",
        "sale_stock",
        "bahmni_sale",
        "bahmni_stock",
        "bahmni_product",
    ],
    "data": [
        "security/cdu_security.xml",
        "security/ir.model.access.csv",
        "data/cdu_sequence.xml",
        "data/cdu_onedrive_cron.xml",
        "data/cdu_collection_point_sync_cron.xml",
        "data/cdu_default_users.xml",
        "data/cdu_rejection_reasons.xml",
        "views/cdu_batch_views.xml",
        "views/cdu_collection_point_views.xml",
        "views/cdu_collection_point_sync_views.xml",
        "views/cdu_facility_views.xml",
        "views/cdu_onedrive_views.xml",
        "views/cdu_patient_views.xml",
        "views/cdu_user_views.xml",
        "wizards/cdu_prescription_reject_wizard_views.xml",
        "wizards/cdu_production_skip_wizard_views.xml",
        "wizards/cdu_report_bulk_import_wizard_views.xml",
        "views/cdu_report_import_views.xml",
        "views/cdu_prescription_views.xml",
        "views/cdu_dashboard_views.xml",
        "views/cdu_product_template_views.xml",
        "views/cdu_regimen_views.xml",
        "views/cdu_menus.xml",
        "data/cdu_data_clerk_home_action.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "cdu_prescription/static/src/css/cdu_design_system.css",
            "cdu_prescription/static/src/css/cdu_prescription_backend.css",
            "cdu_prescription/static/src/css/cdu_production_workspace.css",
            "cdu_prescription/static/src/css/cdu_intake_workspace.css",
            "cdu_prescription/static/src/css/cdu_admin_workspace.css",
            "cdu_prescription/static/src/css/cdu_dashboard.css",
            "cdu_prescription/static/src/css/cdu_tablet.css",
            "cdu_prescription/static/src/js/cdu_dashboard.js",
            "cdu_prescription/static/src/xml/cdu_dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
}
