{
    "name": "CDU Prescription",
    "summary": "Central Dispensing Unit prescription capture and workflow foundation",
    "version": "16.0.1.0.0",
    "category": "Healthcare",
    "author": "Ministry of Health",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "product",
        "stock",
        "sale_stock",
        "bahmni_sale",
        "bahmni_stock",
        "bahmni_product",
    ],
    "data": [
        "security/cdu_security.xml",
        "security/ir.model.access.csv",
        "data/cdu_sequence.xml",
        "data/cdu_onedrive_cron.xml",
        "data/cdu_collection_point_sync_cron.xml",
        "data/cdu_default_users.xml",
        "views/cdu_batch_views.xml",
        "views/cdu_collection_point_views.xml",
        "views/cdu_collection_point_sync_views.xml",
        "views/cdu_facility_views.xml",
        "views/cdu_onedrive_views.xml",
        "views/cdu_patient_views.xml",
        "views/cdu_user_views.xml",
        "views/cdu_report_import_views.xml",
        "views/cdu_prescription_views.xml",
        "views/cdu_product_template_views.xml",
        "views/cdu_regimen_views.xml",
        "views/cdu_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "cdu_prescription/static/src/css/cdu_prescription_backend.css",
        ],
    },
    "installable": True,
    "application": True,
}
